# background_opacity 0.6
# window_padding_width 10

# Font
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 11.5

# Cursor
cursor_shape block
cursor_color #00cfd1
cursor_text_color #0a0a0f

# Background / Foreground
background #050005
foreground #c7d1ff

# Selection
selection_background #7a1cac
selection_foreground #ffffff

# Window
window_padding_width 10
confirm_os_window_close 0

# Transparency (nice with your wallpaper)
background_opacity 0.6

# Tabs
active_tab_background   #7a1cac
active_tab_foreground   #ffffff
inactive_tab_background #111122
inactive_tab_foreground #6a6a9a

# Colors (16 terminal colors)

# Black
color0  #0b0b12
color8  #3a3a55

# Red (magenta tone to match wallpaper)
color1  #c13cff
color9  #e66bff

# Green (cyan tone)
color2  #00cfd1
color10 #33f3f5

# Yellow (soft purple highlight)
color3  #a66bff
color11 #c79aff

# Blue
color4  #3aa0ff
color12 #6bc1ff

# Magenta
color5  #8b3dff
color13 #b47cff

# Cyan
color6  #2de2e6
color14 #6ff7ff

# White
color7  #d9e1ff
color15 #ffffff